### ISSUE TITLE
train with only coco problem

### ISSUE THREAD

**Issue by zhaishengfu** [nkolot/ProHMR#11]
hello， I want to use COCO only to train . I change the dataset.yaml and prohmr.yaml as following:
```
COCO-TRAIN-2014:
    TYPE: ImageDataset
    DATASET_FILE: data/datasets/coco_2014_train_spin.npz
    IMG_DIR: C:/Users/DM/Documents/Code/common_data/train_datasets/COCO/train2014
COCO-VAL:
    TYPE: ImageDataset
    DATASET_FILE: data/datasets/coco_val.npz
    IMG_DIR: C:/Users/DM/Documents/Code/common_data/train_datasets/COCO/val2017
CMU-MOCAP:
    DATASET_FILE: data/datasets/cmu_mocap.npz
```
```
DATASETS:
  TRAIN: 
    COCO-TRAIN-2014:
      WEIGHT: 1.0
  VAL:
    COCO-VAL:
      WEIGHT: 1.0
  MOCAP: CMU-MOCAP
```
and there is error :
**`TypeError: cannot serialize '_io.BufferedReader' object`**
which is caused by 
**File "train/train_prohmr.py", line 63, in <module>
    trainer.fit(model, datamodule=data_module)**

My environment is Win10
